From php:7.4-apache
EXPOSE 80

RUN docker-php-ext-install mysqli
RUN docker-php-ext-enable mysqli
RUN service apache2 restart

COPY index.php /var/www/html/
RUN chown -R www-data:www-data /var/www/html/
RUN chmod o-wx /var/www/html/